language: erlang
otp_release:
  - 17.0
  - 17.1
before_install:
  - git clone https://github.com/elixir-lang/elixir
  - make -C elixir
before_script: "export PATH=`pwd`/elixir/bin:$PATH"
script: mix test
